/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr And</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.ExprAnd#getExprOr1 <em>Expr Or1</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprAnd#getExprOrX <em>Expr Or X</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.WhPackage#getExprAnd()
 * @model
 * @generated
 */
public interface ExprAnd extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr Or1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Or1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Or1</em>' containment reference.
   * @see #setExprOr1(ExprOr)
   * @see org.xtext.comp.wh.WhPackage#getExprAnd_ExprOr1()
   * @model containment="true"
   * @generated
   */
  ExprOr getExprOr1();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprAnd#getExprOr1 <em>Expr Or1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr Or1</em>' containment reference.
   * @see #getExprOr1()
   * @generated
   */
  void setExprOr1(ExprOr value);

  /**
   * Returns the value of the '<em><b>Expr Or X</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.comp.wh.ExprOr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Or X</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Or X</em>' containment reference list.
   * @see org.xtext.comp.wh.WhPackage#getExprAnd_ExprOrX()
   * @model containment="true"
   * @generated
   */
  EList<ExprOr> getExprOrX();

} // ExprAnd
