/*
 * generated by Xtext 2.10.0
 */
package org.comp.python.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWhScopeProvider extends DelegatingScopeProvider {
}
