/**
 * generated by Xtext 2.10.0
 */
package org.comp.python.wh;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.comp.python.wh.WhPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
