/**
 * generated by Xtext 2.10.0
 */
package org.comp.python;

import org.comp.python.AbstractWhRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhRuntimeModule extends AbstractWhRuntimeModule {
}
