/**
 * generated by Xtext 2.10.0
 */
package org.comp.python.ui;

import org.comp.python.ui.AbstractWhUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WhUiModule extends AbstractWhUiModule {
  public WhUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
