/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>cons</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.cons#getList <em>List</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.WhPackage#getcons()
 * @model
 * @generated
 */
public interface cons extends ExprSimple
{
  /**
   * Returns the value of the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' attribute.
   * @see #setList(String)
   * @see org.xtext.comp.wh.WhPackage#getcons_List()
   * @model
   * @generated
   */
  String getList();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.cons#getList <em>List</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' attribute.
   * @see #getList()
   * @generated
   */
  void setList(String value);

} // cons
