/*
 * generated by Xtext 2.10.0
 */
package org.comp.python.ui.tests;

import com.google.inject.Injector;
import org.comp.python.wh.ui.internal.WhActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class WhUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WhActivator.getInstance().getInjector("org.comp.python.Wh");
	}

}
