/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.comp.wh.Cons;
import org.xtext.comp.wh.Expr;
import org.xtext.comp.wh.ExprSimple;
import org.xtext.comp.wh.ListExpr;
import org.xtext.comp.wh.WhPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Simple</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.impl.ExprSimpleImpl#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.comp.wh.impl.ExprSimpleImpl#getStrSymb <em>Str Symb</em>}</li>
 *   <li>{@link org.xtext.comp.wh.impl.ExprSimpleImpl#getCons <em>Cons</em>}</li>
 *   <li>{@link org.xtext.comp.wh.impl.ExprSimpleImpl#getListExpr <em>List Expr</em>}</li>
 *   <li>{@link org.xtext.comp.wh.impl.ExprSimpleImpl#getExprHd <em>Expr Hd</em>}</li>
 *   <li>{@link org.xtext.comp.wh.impl.ExprSimpleImpl#getExprTl <em>Expr Tl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprSimpleImpl extends MinimalEObjectImpl.Container implements ExprSimple
{
  /**
   * The default value of the '{@link #getStr() <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr()
   * @generated
   * @ordered
   */
  protected static final String STR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStr() <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr()
   * @generated
   * @ordered
   */
  protected String str = STR_EDEFAULT;

  /**
   * The default value of the '{@link #getStrSymb() <em>Str Symb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrSymb()
   * @generated
   * @ordered
   */
  protected static final String STR_SYMB_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStrSymb() <em>Str Symb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrSymb()
   * @generated
   * @ordered
   */
  protected String strSymb = STR_SYMB_EDEFAULT;

  /**
   * The cached value of the '{@link #getCons() <em>Cons</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCons()
   * @generated
   * @ordered
   */
  protected Cons cons;

  /**
   * The cached value of the '{@link #getListExpr() <em>List Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListExpr()
   * @generated
   * @ordered
   */
  protected ListExpr listExpr;

  /**
   * The cached value of the '{@link #getExprHd() <em>Expr Hd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprHd()
   * @generated
   * @ordered
   */
  protected Expr exprHd;

  /**
   * The cached value of the '{@link #getExprTl() <em>Expr Tl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprTl()
   * @generated
   * @ordered
   */
  protected Expr exprTl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprSimpleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhPackage.Literals.EXPR_SIMPLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStr()
  {
    return str;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStr(String newStr)
  {
    String oldStr = str;
    str = newStr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__STR, oldStr, str));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStrSymb()
  {
    return strSymb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStrSymb(String newStrSymb)
  {
    String oldStrSymb = strSymb;
    strSymb = newStrSymb;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__STR_SYMB, oldStrSymb, strSymb));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Cons getCons()
  {
    return cons;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCons(Cons newCons, NotificationChain msgs)
  {
    Cons oldCons = cons;
    cons = newCons;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__CONS, oldCons, newCons);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCons(Cons newCons)
  {
    if (newCons != cons)
    {
      NotificationChain msgs = null;
      if (cons != null)
        msgs = ((InternalEObject)cons).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__CONS, null, msgs);
      if (newCons != null)
        msgs = ((InternalEObject)newCons).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__CONS, null, msgs);
      msgs = basicSetCons(newCons, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__CONS, newCons, newCons));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListExpr getListExpr()
  {
    return listExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetListExpr(ListExpr newListExpr, NotificationChain msgs)
  {
    ListExpr oldListExpr = listExpr;
    listExpr = newListExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__LIST_EXPR, oldListExpr, newListExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setListExpr(ListExpr newListExpr)
  {
    if (newListExpr != listExpr)
    {
      NotificationChain msgs = null;
      if (listExpr != null)
        msgs = ((InternalEObject)listExpr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__LIST_EXPR, null, msgs);
      if (newListExpr != null)
        msgs = ((InternalEObject)newListExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__LIST_EXPR, null, msgs);
      msgs = basicSetListExpr(newListExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__LIST_EXPR, newListExpr, newListExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expr getExprHd()
  {
    return exprHd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprHd(Expr newExprHd, NotificationChain msgs)
  {
    Expr oldExprHd = exprHd;
    exprHd = newExprHd;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__EXPR_HD, oldExprHd, newExprHd);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExprHd(Expr newExprHd)
  {
    if (newExprHd != exprHd)
    {
      NotificationChain msgs = null;
      if (exprHd != null)
        msgs = ((InternalEObject)exprHd).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__EXPR_HD, null, msgs);
      if (newExprHd != null)
        msgs = ((InternalEObject)newExprHd).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__EXPR_HD, null, msgs);
      msgs = basicSetExprHd(newExprHd, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__EXPR_HD, newExprHd, newExprHd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expr getExprTl()
  {
    return exprTl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprTl(Expr newExprTl, NotificationChain msgs)
  {
    Expr oldExprTl = exprTl;
    exprTl = newExprTl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__EXPR_TL, oldExprTl, newExprTl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExprTl(Expr newExprTl)
  {
    if (newExprTl != exprTl)
    {
      NotificationChain msgs = null;
      if (exprTl != null)
        msgs = ((InternalEObject)exprTl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__EXPR_TL, null, msgs);
      if (newExprTl != null)
        msgs = ((InternalEObject)newExprTl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhPackage.EXPR_SIMPLE__EXPR_TL, null, msgs);
      msgs = basicSetExprTl(newExprTl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhPackage.EXPR_SIMPLE__EXPR_TL, newExprTl, newExprTl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_SIMPLE__CONS:
        return basicSetCons(null, msgs);
      case WhPackage.EXPR_SIMPLE__LIST_EXPR:
        return basicSetListExpr(null, msgs);
      case WhPackage.EXPR_SIMPLE__EXPR_HD:
        return basicSetExprHd(null, msgs);
      case WhPackage.EXPR_SIMPLE__EXPR_TL:
        return basicSetExprTl(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_SIMPLE__STR:
        return getStr();
      case WhPackage.EXPR_SIMPLE__STR_SYMB:
        return getStrSymb();
      case WhPackage.EXPR_SIMPLE__CONS:
        return getCons();
      case WhPackage.EXPR_SIMPLE__LIST_EXPR:
        return getListExpr();
      case WhPackage.EXPR_SIMPLE__EXPR_HD:
        return getExprHd();
      case WhPackage.EXPR_SIMPLE__EXPR_TL:
        return getExprTl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_SIMPLE__STR:
        setStr((String)newValue);
        return;
      case WhPackage.EXPR_SIMPLE__STR_SYMB:
        setStrSymb((String)newValue);
        return;
      case WhPackage.EXPR_SIMPLE__CONS:
        setCons((Cons)newValue);
        return;
      case WhPackage.EXPR_SIMPLE__LIST_EXPR:
        setListExpr((ListExpr)newValue);
        return;
      case WhPackage.EXPR_SIMPLE__EXPR_HD:
        setExprHd((Expr)newValue);
        return;
      case WhPackage.EXPR_SIMPLE__EXPR_TL:
        setExprTl((Expr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_SIMPLE__STR:
        setStr(STR_EDEFAULT);
        return;
      case WhPackage.EXPR_SIMPLE__STR_SYMB:
        setStrSymb(STR_SYMB_EDEFAULT);
        return;
      case WhPackage.EXPR_SIMPLE__CONS:
        setCons((Cons)null);
        return;
      case WhPackage.EXPR_SIMPLE__LIST_EXPR:
        setListExpr((ListExpr)null);
        return;
      case WhPackage.EXPR_SIMPLE__EXPR_HD:
        setExprHd((Expr)null);
        return;
      case WhPackage.EXPR_SIMPLE__EXPR_TL:
        setExprTl((Expr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WhPackage.EXPR_SIMPLE__STR:
        return STR_EDEFAULT == null ? str != null : !STR_EDEFAULT.equals(str);
      case WhPackage.EXPR_SIMPLE__STR_SYMB:
        return STR_SYMB_EDEFAULT == null ? strSymb != null : !STR_SYMB_EDEFAULT.equals(strSymb);
      case WhPackage.EXPR_SIMPLE__CONS:
        return cons != null;
      case WhPackage.EXPR_SIMPLE__LIST_EXPR:
        return listExpr != null;
      case WhPackage.EXPR_SIMPLE__EXPR_HD:
        return exprHd != null;
      case WhPackage.EXPR_SIMPLE__EXPR_TL:
        return exprTl != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (str: ");
    result.append(str);
    result.append(", strSymb: ");
    result.append(strSymb);
    result.append(')');
    return result.toString();
  }

} //ExprSimpleImpl
