/*
 * generated by Xtext 2.10.0
 */
package org.comp.python.parser.antlr;

import com.google.inject.Inject;
import org.comp.python.parser.antlr.internal.InternalWhParser;
import org.comp.python.services.WhGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WhParser extends AbstractAntlrParser {

	@Inject
	private WhGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWhParser createParser(XtextTokenStream stream) {
		return new InternalWhParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Wh";
	}

	public WhGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WhGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
