/*
 * generated by Xtext 2.10.0
 */
package org.comp.python.ui;

import com.google.inject.Injector;
import org.comp.python.wh.ui.internal.WhActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WhExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WhActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WhActivator.getInstance().getInjector(WhActivator.ORG_COMP_PYTHON_WH);
	}
	
}
