/*
 * generated by Xtext 2.10.0
 */
package org.comp.python


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WhRuntimeModule extends AbstractWhRuntimeModule {
}
