/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Or</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.ExprOr#getExprNot1 <em>Expr Not1</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprOr#getExprNotX <em>Expr Not X</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.WhPackage#getExprOr()
 * @model
 * @generated
 */
public interface ExprOr extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr Not1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Not1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Not1</em>' containment reference.
   * @see #setExprNot1(ExprNot)
   * @see org.xtext.comp.wh.WhPackage#getExprOr_ExprNot1()
   * @model containment="true"
   * @generated
   */
  ExprNot getExprNot1();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprOr#getExprNot1 <em>Expr Not1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr Not1</em>' containment reference.
   * @see #getExprNot1()
   * @generated
   */
  void setExprNot1(ExprNot value);

  /**
   * Returns the value of the '<em><b>Expr Not X</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.comp.wh.ExprNot}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Not X</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Not X</em>' containment reference list.
   * @see org.xtext.comp.wh.WhPackage#getExprOr_ExprNotX()
   * @model containment="true"
   * @generated
   */
  EList<ExprNot> getExprNotX();

} // ExprOr
