/**
 * generated by Xtext 2.10.0
 */
package org.xtext.comp.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getStr <em>Str</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getStrSymb <em>Str Symb</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getCons <em>Cons</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getListExpr <em>List Expr</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getExprHd <em>Expr Hd</em>}</li>
 *   <li>{@link org.xtext.comp.wh.ExprSimple#getExprTl <em>Expr Tl</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.wh.WhPackage#getExprSimple()
 * @model
 * @generated
 */
public interface ExprSimple extends EObject
{
  /**
   * Returns the value of the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Str</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' attribute.
   * @see #setStr(String)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_Str()
   * @model
   * @generated
   */
  String getStr();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getStr <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' attribute.
   * @see #getStr()
   * @generated
   */
  void setStr(String value);

  /**
   * Returns the value of the '<em><b>Str Symb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Str Symb</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str Symb</em>' attribute.
   * @see #setStrSymb(String)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_StrSymb()
   * @model
   * @generated
   */
  String getStrSymb();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getStrSymb <em>Str Symb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str Symb</em>' attribute.
   * @see #getStrSymb()
   * @generated
   */
  void setStrSymb(String value);

  /**
   * Returns the value of the '<em><b>Cons</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cons</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cons</em>' containment reference.
   * @see #setCons(Cons)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_Cons()
   * @model containment="true"
   * @generated
   */
  Cons getCons();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getCons <em>Cons</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cons</em>' containment reference.
   * @see #getCons()
   * @generated
   */
  void setCons(Cons value);

  /**
   * Returns the value of the '<em><b>List Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Expr</em>' containment reference.
   * @see #setListExpr(ListExpr)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_ListExpr()
   * @model containment="true"
   * @generated
   */
  ListExpr getListExpr();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getListExpr <em>List Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Expr</em>' containment reference.
   * @see #getListExpr()
   * @generated
   */
  void setListExpr(ListExpr value);

  /**
   * Returns the value of the '<em><b>Expr Hd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Hd</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Hd</em>' containment reference.
   * @see #setExprHd(Expr)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_ExprHd()
   * @model containment="true"
   * @generated
   */
  Expr getExprHd();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getExprHd <em>Expr Hd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr Hd</em>' containment reference.
   * @see #getExprHd()
   * @generated
   */
  void setExprHd(Expr value);

  /**
   * Returns the value of the '<em><b>Expr Tl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Tl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Tl</em>' containment reference.
   * @see #setExprTl(Expr)
   * @see org.xtext.comp.wh.WhPackage#getExprSimple_ExprTl()
   * @model containment="true"
   * @generated
   */
  Expr getExprTl();

  /**
   * Sets the value of the '{@link org.xtext.comp.wh.ExprSimple#getExprTl <em>Expr Tl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr Tl</em>' containment reference.
   * @see #getExprTl()
   * @generated
   */
  void setExprTl(Expr value);

} // ExprSimple
